### ISSUE TITLE
StackOverFlowException when serializing a graph

### ISSUE THREAD

**Issue by ab-tools** [antmicro/Migrant#111]
I'm trying to migrate from protobuf-net to Migrant as I constantly have problems with protobuf-net when trying to use it with graph structures. Although protobuf-net states to support "object by reference" since version 2, this just seems not to work correctly.

I did some test with Migrant, but unfortunately I also have a problem with that.

Not sure if I'm just doing something wrong or if that's a bug. Therefore I created an example project to reproduce the problems I have:

StackOverFlowException when serializing a graph - reproduce with example project sent via e-mail as following:
- start project.
- click on button "Load Data With Protobuf" to get the example data into memory.
- click on button "Save Data Wtih Migrant" to store it again.
=> this will result in a StackOverFlowException and the reason is property "Airways" in object "Waypoint".
=> Why this is a problem?
If everything is saved as reference it should work smoothly or did I miss something?

If you add the attribute "[Antmicro.Migrant.Transient]" to the property "Airways" in object "Waypoint" Migrant can serialize the database without problems, but why this is needed?

I did not include the example project in this post here, but send it to the e-mail address of the first author “Konrad Kruczyński” mentioned on the GitHub page, as I do need to include quite a lot data with it to be able to reproduce the problem. Please don’t share this data publically.

**Comment by mateusz-holenko** [comment]
Hi! Thank you for a detailed report of the problem and for the source code. It helped us greatly when looking for fragments of code responsible for the exception.

As it turned out, the problem lies with a depth of `Airways` and `Waypoints` graph (about 45 000 levels) and the way we serialize this data. In our approach we serialize new objects right where they were first spotted, which requires us to call methods recursively. As the example shows this approach is not suitable for serialization of objects that have very deep nesting.

In the example `Airways` object has references to `Waypoints` and `Waypoints` references `Airways`. This creates a very long chain of objects `Airways`=>`Waypoints`=>`Airways`=>...=>`Waypoints` which exhausts available stack frames.
Of course using `Transient` attribute solves the problem by reducing the depth (chain length), but I am not sure if it is an acceptable solution for you.

Proper solution would require us to change internals of a library and, probably, format of serialized data. We have to analyze it and discuss throughly before making any decisions. Please stay tuned!

**Comment by PiotrZierhoffer** [comment]
Please bear in mind, that having a transient field would require a `[Late]PostDeserializationAttribute`-method to rebuild it. We believe that in your case it is possible to do so, am I right?

But, as Mateusz said, this problem is interesting and more general than your case, so we will definitely think about a proper solution.

**Comment by ab-tools** [comment]
First thanks a lot for your quick reaction and sorry that I did not reply till now (strangely I did not receive an e-mail notification from GitHub about your reply and therefore just saw it right now).

Yes, I could use `PostDeserializationAttribute`, but as you wrote already it's not a clean approach and I really would like to switch to a serialization framework (away from protobuf-net) that does not have these problems anymore and doesn’t need such ugly work-arounds.

But anyway, I've tried that now (maybe as interim solution) and encountered another very strange issue:
- I completely rebuild the database from scratch (without loading it from the "protobuf-net" database).
- then I serialized the data with the `PostDeserializationAttribute` in place (which worked fine).
- now I closed the program and restarted it immediately without a single line of code changed.
=> upon loading the previously saved database with Migrant again it complains about the type of field `m_contents` in object `DatabaseNode` being changed although it obviously was not changed as it's still the exactly same code.

Unfortunately I was only able to reproduce this problem when rebuilding the database from scratch before saving it and not when loading it from the protobuf example database I sent to you.

I cannot send you the whole project code for building the complete database obviously, but if you really would like to track-down this issue, I would be happy to do a TeamViewer session with you and show you the problem directly. I would set everything up in a way that you could debug remotely then.

Please just contact me over Skype (user name "ab-tools").

Thank you again a lot for your quick reaction and support!
Andreas

**Comment by mateusz-holenko** [comment]
Do you rebuild the assembly where `m_contents` type is located between serialization and deserialization? Probably not, so it looks like an issue we should investigate. Could your send us serialized database file together with binary and sources of serializer/deserializer, but this time direct it to migrant@antmicro.com? I'm afraid we won't be able to conduct interactive debugging session in the near future due to time constraints on other projects.

**Comment by ab-tools** [comment]
Hello Mateusz,

first thanks a lot for your quick reply again!

I just sent you an e-mail with another example project to reproduce the problem upon deserialization.

But regarding your question:
yes, the assembly was rebuild after serialization and before deserialization, but this should not be a problem as long as no code is changed, is it?

Best regards and thanks again
Andreas

**Comment by ab-tools** [comment]
Hello Mateusz,

did you find out something about this problem?
I would really like to get rid of protobuf. ;-)

Best regards
Andreas

**Comment by mateusz-holenko** [comment]
Hello Andreas,

first sorry for a delay, but we are having a quite busy time at Antmicro right now. 

The good news is that we succeeded in localizing the problem - the bug is related to resolving generic types. Unfortunately it requires deeper analysis and tests and I'm afraid  we are not able to fix it right now. We have already scheduled it to the beginning of the next month and will inform you ASAP about the progress.

Best regards,
Mateusz

**Comment by mateusz-holenko** [comment]
Hello again,

@konrad-kruczynski has just suggested to me that you can always use setting called `DisableTypeStamping` in order to disable the faulty mechanism. It might be a temporary workaround that would be easily revertible after our fix.

Hope this helps for now,
Mateusz

**Comment by ab-tools** [comment]
Hello Mateusz,

first thanks a lot for your reply now!

If that is possible and you need to do a deeper analyze anyway, it would be really great if you also could fix the main problem regarding serializing a graph like in my first example at the beginning of next month.

Regarding the temporary work-around:
may I ask what the setting "DisableTypeStamping" does?
As it is not set by default although it increases performance (according to your code documentation) I guess there is a reason for it.;-)
So what is the drawback of using this setting?

Best regards and thanks again
Andreas

**Comment by mateusz-holenko** [comment]
Type stamping is a part of version tolerance mechanism that is used to detect changes in class layouts between serialization/deserialization. It allows us to skip fields that were removed or properly initialize the new one.

It is useful only when you assume that format of your serialized data might be changing and your application should handle both old and new versions of serialized data.

If the layout has changed and this option is disabled, Migrant will not be able to deserialize data correctly.

**Comment by ab-tools** [comment]
That's indeed a problem as I do need this kind of version tolerance:
currently with "protobuf" I'm able to use the "[ProtoMember(i)]" attribute to define which property is included and due to the numbering I can easily add new and remove old properties.

So I'm afraid I will need to wait till this bug has been fixed.

My product is still in development and therefore I can change the serialization framework currently very easily, but will need to commit to one before the first official release probably in 2-3 weeks.

But if you can fix the bugs at the beginning of next months I really like to change from "protobuf" to Migrant. There is really no support at all for "protobuf" (posted the object reference bugs there weeks ago and never get a single reply).

Therefore maybe Migrant could get the "new protobuf" in terms of spread as there is in my opinion really a demand for a good and stable serialization framework able to handle object reference and graphs correctly. I searched a lot and did not find a single one working correctly.
So I'm really looking forward to your fixes! :-)

Best regards and thanks again a lot for your support
Andreas

**Comment by ab-tools** [comment]
Hello Mateusz,

just wanted to let you know that I found this fork of "protobuf-net" we seems to work fine with my data structure:
https://github.com/AqlaSolutions/AqlaSerializer

The only problem left is the StackOverFlowException due to the large graph structure, but there is a work-around for it:
if you do the serialization and deserialization in a new thread and start this thread with a higher maximum stack size (like 20 MB instead of the default of 1 MB), it works fine.

If you get this StackOverFlowException fixed for Migrant I would still like to use your system (as I don't need any work-around then), but otherwise I probably will stick to this "AqlaSerializer" now.

Anyway, thanks for your support again
Andreas

**Comment by konrad-kruczynski** [comment]
We finally had some discussions about the solution for the stack overflow problem. This will also resolve  other problematic scenarios in which delegated to be deserialized referenced an object that sooner or later reference that delegate again. I'll inform you when some code lands in the repository.

**Comment by mateusz-holenko** [comment]
It took much longer than we expected, but finally the new version of Migrant is released. We had to redesign the entire data format in order to support deep graphs and avoid `StackOverflowException`.
