### ISSUE TITLE
Serializing type that contains a Type property seems to throw

### ISSUE THREAD

**Issue by rogeralsing** [antmicro/Migrant#86]
[Edit]
It looks like there is a problem with serializing `Type` properties

I'm getting the following exception from insde Migrant:

`[System.InvalidOperationException] = {"Pointer or ThreadLocal or SpinLock encountered during serialization. The classes path that lead to it was: DeployableDecider => KeyValuePair`2[] => RuntimeType"}`

and

`[System.InvalidOperationException] = {"Pointer or ThreadLocal or SpinLock encountered during serialization. The classes path that lead to it was: OneForOneStrategy => OneForOneStrategySurrogate => 
DeployableDecider => KeyValuePair`2[] => RuntimeType"}`

And `[System.InvalidOperationException] = {"Pointer or ThreadLocal or SpinLock encountered during serialization. The classes path that lead to it was: Props => PropsSurrogate => RuntimeType"}`

Is it a known problem?

**Comment by rogeralsing** [comment]
Creating a surrogate for `Type` solves the problem

**Comment by konrad-kruczynski** [comment]
Serializing type directly is not currently possible. It is known limitation rather than bug, since the type is different between frameworks (.NET, Mono) and contains pointers.

Surrogate is one possibility to resolve this problem. However I'm curious what surrogate have you used. The point is that one can e.g. save the fully qualified name of the type to the string and use that as a surrogate (and analogically the other way round). This approach has, however, some flaws - the same we were struggling with saving type information in Migrant's metadata. What about using those metadata to save **your** type information. Example solution could look like that:

    class MainClass
	{
		public static void Main(string[] args)
		{
			var serializer = new Serializer();
			serializer.ForObject<Type>().SetSurrogate(type => Activator.CreateInstance(typeof(TypeSurrogate<>).MakeGenericType(new [] { type })));
			serializer.ForSurrogate<ITypeSurrogate>().SetObject(x => x.Build());

			var tab = new [] { typeof(int), typeof(int[]), typeof(MainClass) };

			var stream = new MemoryStream();
			serializer.Serialize(tab, stream);
			stream.Seek(0, SeekOrigin.Begin);
			var something = serializer.Deserialize<Type[]>(stream);
			foreach(var s in something)
			{
				Console.WriteLine(s);
			}
		}
	}

	public class TypeSurrogate<T> : ITypeSurrogate
	{
		public Type Build()
		{
			return typeof(T);
		}		
	}

	public interface ITypeSurrogate
	{
		Type Build();
	}

It works, however is definitely not of the best performance due to reflection. This could be significantly improved using some caching. Does that solution suits you? If it does, we could think about integrating this surrogate in Migrant internally so it will  be able to handle the type ``Type`` out of the box.

**Comment by rogeralsing** [comment]
I currently use the fully qualified typename in my surrogate.
The code can be seen here: https://github.com/akkadotnet/akka.net/pull/1232/files#diff-e7ab9be39729a756b0e017976caea87eR8

That is the same approach as Json.NET uses afaik as the typename is embedded inside the json objects as a `$type` field and that have worked fine so far.
What are the specific flaws that can arise from using the qualified name ?

So far I'm extremely impressed with this lib, it handles everything I have thrown at it, even Linq Expressions.

**Comment by konrad-kruczynski** [comment]
The flaws I had on mind are related to version tolerance. After thinking a while about it, it actually may not be a problem for you at all. Because we write all fields of the type, we have to check whether type structure during deserialization is compatible with the state encountered during serialization. This may or may not be the case for you - and probably is not. In that case you can perfectly stick with your solution.

You can, however, still benefit from caching (i.e. having string to type map instead of calling Type.GetType each time), especially if there are many objects of the same type.

**Comment by konrad-kruczynski** [comment]
Ok, I've updated the README file to mention both methods of serializing type, you can look at it here: https://github.com/antmicro/Migrant#deserializing-the-type-type

Do you have anything else to add? If no, I think we can close the issue :)

**Comment by rogeralsing** [comment]
Thanks, things seems to work fine for us now so Im closing this issue
